table Amazon
	lineageTag: 039b4ccb-d2b6-40c6-a275-a678bfaab566

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3468a5b8-7b8c-4a56-9d10-701ae18760d0
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 449f4320-fc92-4f57-a526-d11ebc72357e
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: f3090e8b-85c5-41f4-80a3-b7c5790a6c41
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 94cbc264-0116-42c7-9078-e65a6bc7c753
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 5097819d-2e77-48ee-a2da-1dcc2f8de738
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 046a61e7-709e-4389-a104-4a5a371e4085
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: a690f180-7e9a-4977-9e27-287e90a829a4
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition Amazon = m
		mode: import
		source =
				let
				
				    Source = AzureStorage.DataLake("https://onelake.dfs.fabric.microsoft.com/NewWorkspace/Lakehouse1.Lakehouse/Files/Amazon.csv"),
				    #"https://onelake dfs fabric microsoft com/NewWorkspace/Lakehouse1 Lakehouse/Files/_Amazon csv" = Source{[#"Folder Path"="https://onelake.dfs.fabric.microsoft.com/NewWorkspace/Lakehouse1.Lakehouse/Files/",Name="Amazon.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"https://onelake dfs fabric microsoft com/NewWorkspace/Lakehouse1 Lakehouse/Files/_Amazon csv",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

